# Generated by Django 2.0.5 on 2018-05-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(max_length=2)),
                ('district_code', models.CharField(max_length=5)),
                ('school_code', models.CharField(max_length=7)),
                ('test_year', models.IntegerField()),
                ('county_name', models.CharField(max_length=200)),
                ('district_name', models.CharField(blank=True, max_length=1000)),
                ('school_name', models.CharField(blank=True, max_length=1000)),
                ('zipcode', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Type', to_field='type_id'),
        ),
    ]
