# Generated by Django 2.0.5 on 2018-05-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180516_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='type_id',
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='api.Type', to_field='type_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type_id',
            field=models.IntegerField(unique=True),
        ),
    ]
