# Generated by Django 2.0.5 on 2018-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_group_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
