# Generated by Django 2.0.5 on 2018-05-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180520_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='category',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
